version: "3.8"

services:
  auth:
    build:
      context: .
      dockerfile: ./apps/auth-microservice/Dockerfile
    container_name: auth-microservice
    env_file:
      - env/dev/.env.common
      - env/dev/.env.auth
    ports:
      - "8081:8081"
    networks:
      - app-net

  event:
    build:
      context: .
      dockerfile: ./apps/event-microservice/Dockerfile
    container_name: event-microservice
    env_file:
      - env/dev/.env.common
      - env/dev/.env.event
    ports:
      - "8082:8082"
    networks:
      - app-net

  gateway:
    build:
      context: .
      dockerfile: ./apps/gateway/Dockerfile
    container_name: api-gateway
    env_file:
      - env/dev/.env.common
      - env/dev/.env.gateway
    ports:
      - "8080:8080"
    depends_on:
      - auth
      - event
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
